"use client";

import { useEffect, useMemo, useState } from "react";
import { DateTime } from "luxon";

import UpdateCard from "../components/UpdateCard";
import type { SnapshotData } from "../lib/types";

type LoadState =
  | { kind: "loading" }
  | { kind: "error"; message: string }
  | { kind: "ready"; data: SnapshotData };

async function fetchSnapshot(): Promise<SnapshotData> {
  const resp = await fetch("/data/latest.json", { cache: "no-store" });
  if (resp.status === 404) {
    // Snapshot not published yet (e.g., before the first successful daily run).
    return {
      digest_date: "",
      generated_at: null,
      counts: { urgent: 0, federal: 0, state: 0, watchlist: 0 },
      updates: [],
      markdown: null
    };
  }
  if (!resp.ok) {
    throw new Error(`Snapshot not found: /data/latest.json (${resp.status})`);
  }
  return (await resp.json()) as SnapshotData;
}

export default function HomePage() {
  const [state, setState] = useState<LoadState>({ kind: "loading" });

  useEffect(() => {
    let mounted = true;
    fetchSnapshot()
      .then((data) => {
        if (mounted) setState({ kind: "ready", data });
      })
      .catch((e) => {
        if (mounted) setState({ kind: "error", message: e instanceof Error ? e.message : String(e) });
      });
    return () => {
      mounted = false;
    };
  }, []);

  const tz = useMemo(() => process.env.NEXT_PUBLIC_DIGEST_TIMEZONE || "America/Los_Angeles", []);
  const expectedDate = useMemo(
    () => DateTime.now().setZone(tz).toISODate() || DateTime.utc().toISODate()!,
    [tz]
  );

  if (state.kind === "loading") {
    return (
      <div className="card">
        <div className="title">Loading…</div>
        <div className="meta">Fetching the latest daily snapshot.</div>
      </div>
    );
  }

  if (state.kind === "error") {
    return (
      <div className="card">
        <div className="title">Dashboard not ready</div>
        <div className="meta">
          The dashboard reads from <code>/data/latest.json</code> (generated by the daily pipeline run). If you just
          deployed, wait for the next 7:00 AM run or run the pipeline manually.
        </div>
        <details>
          <summary>Show error</summary>
          <pre>{state.message}</pre>
        </details>
      </div>
    );
  }

  const data = state.data;
  const isForToday = data.digest_date === expectedDate;
  const display = isForToday
    ? data
    : {
        digest_date: expectedDate,
        generated_at: null,
        counts: { urgent: 0, federal: 0, state: 0, watchlist: 0 },
        updates: [],
        markdown: null
      };

  const todayLabel = DateTime.fromISO(display.digest_date).toLocaleString(DateTime.DATE_FULL);
  const generatedLabel = display.generated_at
    ? DateTime.fromISO(display.generated_at).toLocaleString(DateTime.DATETIME_MED_WITH_SECONDS)
    : "unknown";

  return (
    <>
      <div className="header">
        <div>
          <h2>Today’s Update</h2>
          <div className="subheader">
            Date: <strong>{todayLabel}</strong> • Generated: <strong>{generatedLabel}</strong>
          </div>
        </div>
        <div className="subheader">Refresh cadence: once daily after the 7:00 AM pipeline run ({tz})</div>
      </div>

      <div className="grid">
        <div className="stat">
          <div className="label">Urgent</div>
          <div className="value">{display.counts.urgent}</div>
        </div>
        <div className="stat">
          <div className="label">Federal</div>
          <div className="value">{display.counts.federal}</div>
        </div>
        <div className="stat">
          <div className="label">State</div>
          <div className="value">{display.counts.state}</div>
        </div>
        <div className="stat">
          <div className="label">Watchlist</div>
          <div className="value">{display.counts.watchlist}</div>
        </div>
      </div>

      {!isForToday ? (
        <div className="card">
          <div className="title">Today’s digest isn’t available yet</div>
          <div className="meta">Check back after the scheduled 7:00 AM pipeline run ({tz}).</div>
        </div>
      ) : display.updates.length === 0 ? (
        <div className="card">
          <div className="title">No significant updates</div>
          <div className="meta">
            No items were included in today’s snapshot. The raw digest markdown (if present) is still available below.
          </div>
        </div>
      ) : (
        <div className="feed">
          {display.updates.map((u) => (
            <UpdateCard key={u.id} update={u} />
          ))}
        </div>
      )}

      <details>
        <summary>View raw digest markdown (source of truth)</summary>
        <pre>{display.markdown ?? "No digest markdown found in snapshot."}</pre>
      </details>
    </>
  );
}
